cujarrett/destiny-insights-backend

src/util/get-last-sold-message.js
test/unit/get-last-sold-message.js

fix: corrects last sold info

---

src/routes/info.js

returns error object instead of a string

fix: returns error object

---

package-lock.json
src/routes/info.js

- adds limited manifest retries to add reliability

fix: adds limited manifest retries to add reliability

---

package-lock.json
src/routes/info.js

- Increase manifest retries to 5 from 3
- Adds additional manifest retry logging
- Adds error message to response in `response.metadata.error`

Increase manifest retries

---

package-lock.json
src/data/known-mods.js
src/routes/info.js
src/util/check-if-token-refresh-needed.js
src/util/get-banshee-inventory-endpoint.js
src/util/get-banshee-inventory.js
src/util/get-categories.js
src/util/get-manifest-data.js
src/util/get-mods.js
src/util/get-valid-auth.js
src/util/process-last-updated.js
src/util/refresh-token.js
test/unit/check-if-token-refresh-needed.js
test/unit/get-categories.js

- feat: refactors info endpoint

feat: refactors info endpoint

---

package-lock.json
src/integrations/dynamodb.js
src/routes/get-mod-data-for-last-year.js

- Adds dynamic mod type lookup to `/get-mod-data-for-last-year`

feat: adds dynamic mod type lookup

---

.github/CODEOWNERS

fix: fixes CODEOWNERS

---

src/data/cached-mods.json
src/util/build-cached-mods.js
test/unit/get-mods.js

fix: mod descriptions when perk info available

fix: mod descriptions when perk info available

---

src/integrations/dynamodb.js
src/util/process-last-updated.js

fix: last updated and new mod check

fix: last updated and new mod check

---

src/util/get-xur-inventory.js

Fixes /xur endpoint when Xur has no inventory (Monday through Thursday resets)

fix: handles empty Xur inventory days

---

src/util/get-xur-inventory.js
terraform/main.tf
terraform/modules/dynamodb/main.tf
terraform/modules/iam/main.tf
terraform/modules/iam/variables.tf

Add notable vendor armor IaC

---

terraform/modules/iam/main.tf

Renames AWS IAM names to be kebab case

feat: renames iam names

---

terraform/modules/dynamodb/main.tf

Increase mods table provisioned reads to 15

feat: increase mods table provisioned reads to 15

---

terraform/main.tf
terraform/modules/dynamodb/main.tf
terraform/modules/iam/main.tf
terraform/modules/iam/variables.tf

feat: renames vendor armor database

---

CONTRIBUTING.md
README.md

feat: updates docs after rebrand

---

terraform/main.tf
terraform/modules/dynamodb/main.tf
terraform/modules/iam/main.tf
terraform/modules/iam/variables.tf

- Removes vendor armor database

feat: removes vendor armor database

---

src/util/get-xur-inventory.js

Removes redundant xurItemComponents creation

fix: removes redundant xurItemComponents creation

---

src/integrations/dynamodb.js

fix: mods last updated logic

---

package-lock.json
package.json
src/util/get-ada-1-inventory.js
src/util/get-banshee-44-inventory.js

- Fix late update last updated bug caused by late Bungie API the day before causing more than normal mods being sold within 24 hours
- Updated dependencies

Fix late update last updated bug

---

src/integrations/dynamodb.js
src/util/get-ada-1-inventory.js
src/util/get-banshee-44-inventory.js

Fixes bug for last sold mods when Bungie API is down at reset the day before.

fix: bug for last sold mods

---

package-lock.json
package.json
src/integrations/dynamodb.js
src/util/get-ada-1-inventory.js
src/util/get-banshee-44-inventory.js
src/util/is-same-inventory.js

adds new inventory double check

feat: adds new inventory double check

---

src/util/get-ada-1-inventory.js
src/util/get-banshee-44-inventory.js

fix: returns correct mods if double check fails

fix: returns correct mods if double check fails

---

src/routes/ada-1.js
src/routes/banshee-44.js
src/routes/xur.js

feat: removes metadata version

feat: removes metadata version

---

.github/workflows/update.yml

fix: update cache job

---

.github/workflows/update.yml

feat: adds reviewer

---

.github/workflows/update.yml

fix: updates update-cache commit message config

fix: updates update-cache commit message config

---

terraform/main.tf
terraform/modules/iam/main.tf
terraform/modules/iam/variables.tf
terraform/variables.tf

feat: updates mods table access

feat: updates mods table access

---

src/util/get-vendor-inventory.js

fix: fix empty vendor inventory to match norm

fix: fix empty vendor inventory

---

src/util/get-vendor-inventory.js

fix: patch weapon sword support

fix: patch weapon sword support

---

terraform/modules/api_gateway/main.tf

feat: refactor api-gateway

---

terraform/modules/api_gateway/main.tf

feat: adds custom domain

---

terraform/main.tf
terraform/modules/api_gateway/main.tf
terraform/modules/api_gateway/variables.tf
terraform/modules/archive/main.tf
terraform/modules/iam/variables.tf
terraform/modules/lambda/main.tf
terraform/modules/lambda/variables.tf
terraform/variables.tf

feat: disable execute endpoint

feat: disable execute endpoint

---

src/util/get-vendor-inventory.js

fix: adds support for multiple sword perk locations

fix: adds support for multiple sword perk locations

---

src/data/cached-items.json
src/data/cached-mods.json
src/util/get-vendor-inventory.js

feat: adds support for witch queen

feat: adds support for witch queen

---

src/util/get-vendor-inventory.js

feat: adds support for Xur selling Hawkmoon and Dead Mans Tale

feat: adds support for Xur selling Hawkmoon and Dead Mans Tale

---

src/util/get-vendor-inventory.js

fix: weapon perk logic

---

.github/workflows/test.yml

chore: runs tests on forks

---

src/util/get-vendor-inventory.js

fix: removes trackers from perks listed (#250)

fix: removes trackers from perks listed

---

package-lock.json
src/data/cached-items.json

feat: updates cache

---

package.json
src/data/cached-items.json
src/data/cached-mods.json
test/integration/build-cached-mods.js

fix: updates cache

---

src/util/build-cached-weapon-wish-lists.js

- chore: updates cache
- chore: adds saftey check for invalid itemhashes in wish list data

chore: updates cache

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update-cache.yml
.github/workflows/update-dependencies.yml

fix: updates cicd

---

package-lock.json
package.json
test/integration/build-cached-mods.js
test/integration/devrim-kay.js
test/integration/failsafe.js

fix: updates dependencies

---

terraform/modules/dynamodb/main.tf

feat: adds consumer auth table

feat: adds consumer auth table

---

terraform/modules/dynamodb/main.tf

fix: fixes  consumer auth table name

fix: fixes  consumer auth table name
